@url = http://localhost:6005/api/booking
@id = 66a9ec97b1d1161fab38f7e1
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJiODdiMjgzZGE1OTRmODJjNzZhNmQiLCJpYXQiOjE3MDgzMzI0NjYsImV4cCI6MTcxMTg5ODg2Nn0.XkzmVb4w6BdqurNIYTYttp0SEdFu8bTrWFJJhCMreWA


###
GET {{url}}/{{id}}
Content-Type: application/json

###
POST {{url}}/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "room_slug": "the-leela-palace-business-suite-501",
    "date": "2024-08-26T16:00:00Z",
    "check_in": "2024-09-03T14:00:00Z",
    "check_out": "2024-09-07T12:00:00Z",
    "total_price": 80000,
    "guests": [
      {
        "name": "Anil Mehta",
        "age": 40
      },
      {
        "name": "Rita Mehta",
        "age": 38
      }
    ]
  }