@url = http://localhost:6001/booking
@id = 66a9ec97b1d1161fab38f7e1


###
GET {{url}}/{{id}}
Content-Type: application/json

###
POST {{url}}/
Content-Type: application/json

{
  "room_slug": "leela-standard-101",
  "user_id": "64c7cfa16f5e2e3a9b5f4e1d",
  "check_in": "2021-12-01",
  "check_out": "2021-12-03",
  "guests": [
    {
      "name": "John Doe",
      "age": 30
      },
      {
      "name": "Jane Doe",
      "age":12}],
  "total_price": 10000

}